<?php

namespace VetoPlatformBundle\Repository;

/**
 * ClasseAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
